/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'
import { Route as AuthenticatedAdminGatesRouteImport } from './routes/_authenticated.admin.gates'
import { Route as AuthenticatedAdminMoteursRouteImport } from './routes/_authenticated.admin.moteurs'
import { Route as AuthenticatedAdminProjetsRouteImport } from './routes/_authenticated.admin.projets'
import { Route as AuthenticatedAdminSanteRouteImport } from './routes/_authenticated.admin.sante'
import { Route as AuthenticatedAdminSecuriteRouteImport } from './routes/_authenticated.admin.securite'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated.admin.usage'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated.admin.utilisateurs'
import { Route as AuthenticatedProjetsIndexRouteImport } from './routes/_authenticated.projets.index'
import { Route as AuthenticatedProjetsIdRouteImport } from './routes/_authenticated.projets.$id'
import { Route as ApiCaSplatRouteImport } from './routes/api/ca.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGatesRoute = AuthenticatedAdminGatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMoteursRoute =
  AuthenticatedAdminMoteursRouteImport.update({
    id: '/moteurs',
    path: '/moteurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjetsRoute =
  AuthenticatedAdminProjetsRouteImport.update({
    id: '/projets',
    path: '/projets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSanteRoute = AuthenticatedAdminSanteRouteImport.update({
  id: '/sante',
  path: '/sante',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSecuriteRoute =
  AuthenticatedAdminSecuriteRouteImport.update({
    id: '/securite',
    path: '/securite',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedProjetsIndexRoute =
  AuthenticatedProjetsIndexRouteImport.update({
    id: '/projets/',
    path: '/projets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjetsIdRoute = AuthenticatedProjetsIdRouteImport.update({
  id: '/projets/$id',
  path: '/projets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiCaSplatRoute = ApiCaSplatRouteImport.update({
  id: '/api/ca/$',
  path: '/api/ca/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/gates': typeof AuthenticatedAdminGatesRoute
  '/admin/moteurs': typeof AuthenticatedAdminMoteursRoute
  '/admin/projets': typeof AuthenticatedAdminProjetsRoute
  '/admin/sante': typeof AuthenticatedAdminSanteRoute
  '/admin/securite': typeof AuthenticatedAdminSecuriteRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/projets/$id': typeof AuthenticatedProjetsIdRoute
  '/api/ca/$': typeof ApiCaSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/projets/': typeof AuthenticatedProjetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tarifs': typeof TarifsRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/gates': typeof AuthenticatedAdminGatesRoute
  '/admin/moteurs': typeof AuthenticatedAdminMoteursRoute
  '/admin/projets': typeof AuthenticatedAdminProjetsRoute
  '/admin/sante': typeof AuthenticatedAdminSanteRoute
  '/admin/securite': typeof AuthenticatedAdminSecuriteRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/projets/$id': typeof AuthenticatedProjetsIdRoute
  '/api/ca/$': typeof ApiCaSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/projets': typeof AuthenticatedProjetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/gates': typeof AuthenticatedAdminGatesRoute
  '/_authenticated/admin/moteurs': typeof AuthenticatedAdminMoteursRoute
  '/_authenticated/admin/projets': typeof AuthenticatedAdminProjetsRoute
  '/_authenticated/admin/sante': typeof AuthenticatedAdminSanteRoute
  '/_authenticated/admin/securite': typeof AuthenticatedAdminSecuriteRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/projets/$id': typeof AuthenticatedProjetsIdRoute
  '/api/ca/$': typeof ApiCaSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/projets/': typeof AuthenticatedProjetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/tarifs'
    | '/admin'
    | '/api/chat'
    | '/admin/audit'
    | '/admin/gates'
    | '/admin/moteurs'
    | '/admin/projets'
    | '/admin/sante'
    | '/admin/securite'
    | '/admin/usage'
    | '/admin/utilisateurs'
    | '/projets/$id'
    | '/api/ca/$'
    | '/admin/'
    | '/projets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/tarifs'
    | '/api/chat'
    | '/admin/audit'
    | '/admin/gates'
    | '/admin/moteurs'
    | '/admin/projets'
    | '/admin/sante'
    | '/admin/securite'
    | '/admin/usage'
    | '/admin/utilisateurs'
    | '/projets/$id'
    | '/api/ca/$'
    | '/admin'
    | '/projets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/tarifs'
    | '/_authenticated/admin'
    | '/api/chat'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/gates'
    | '/_authenticated/admin/moteurs'
    | '/_authenticated/admin/projets'
    | '/_authenticated/admin/sante'
    | '/_authenticated/admin/securite'
    | '/_authenticated/admin/usage'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/projets/$id'
    | '/api/ca/$'
    | '/_authenticated/admin/'
    | '/_authenticated/projets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  TarifsRoute: typeof TarifsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCaSplatRoute: typeof ApiCaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gates': {
      id: '/_authenticated/admin/gates'
      path: '/gates'
      fullPath: '/admin/gates'
      preLoaderRoute: typeof AuthenticatedAdminGatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moteurs': {
      id: '/_authenticated/admin/moteurs'
      path: '/moteurs'
      fullPath: '/admin/moteurs'
      preLoaderRoute: typeof AuthenticatedAdminMoteursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projets': {
      id: '/_authenticated/admin/projets'
      path: '/projets'
      fullPath: '/admin/projets'
      preLoaderRoute: typeof AuthenticatedAdminProjetsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sante': {
      id: '/_authenticated/admin/sante'
      path: '/sante'
      fullPath: '/admin/sante'
      preLoaderRoute: typeof AuthenticatedAdminSanteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/securite': {
      id: '/_authenticated/admin/securite'
      path: '/securite'
      fullPath: '/admin/securite'
      preLoaderRoute: typeof AuthenticatedAdminSecuriteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/projets/': {
      id: '/_authenticated/projets/'
      path: '/projets'
      fullPath: '/projets/'
      preLoaderRoute: typeof AuthenticatedProjetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projets/$id': {
      id: '/_authenticated/projets/$id'
      path: '/projets/$id'
      fullPath: '/projets/$id'
      preLoaderRoute: typeof AuthenticatedProjetsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/ca/$': {
      id: '/api/ca/$'
      path: '/api/ca/$'
      fullPath: '/api/ca/$'
      preLoaderRoute: typeof ApiCaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminGatesRoute: typeof AuthenticatedAdminGatesRoute
  AuthenticatedAdminMoteursRoute: typeof AuthenticatedAdminMoteursRoute
  AuthenticatedAdminProjetsRoute: typeof AuthenticatedAdminProjetsRoute
  AuthenticatedAdminSanteRoute: typeof AuthenticatedAdminSanteRoute
  AuthenticatedAdminSecuriteRoute: typeof AuthenticatedAdminSecuriteRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminGatesRoute: AuthenticatedAdminGatesRoute,
  AuthenticatedAdminMoteursRoute: AuthenticatedAdminMoteursRoute,
  AuthenticatedAdminProjetsRoute: AuthenticatedAdminProjetsRoute,
  AuthenticatedAdminSanteRoute: AuthenticatedAdminSanteRoute,
  AuthenticatedAdminSecuriteRoute: AuthenticatedAdminSecuriteRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProjetsIdRoute: typeof AuthenticatedProjetsIdRoute
  AuthenticatedProjetsIndexRoute: typeof AuthenticatedProjetsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProjetsIdRoute: AuthenticatedProjetsIdRoute,
  AuthenticatedProjetsIndexRoute: AuthenticatedProjetsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  TarifsRoute: TarifsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCaSplatRoute: ApiCaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
