/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as Demo3dRouteImport } from './routes/demo3d'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedProjetsIndexRouteImport } from './routes/_authenticated.projets.index'
import { Route as AuthenticatedProjetsIdRouteImport } from './routes/_authenticated.projets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Demo3dRoute = Demo3dRouteImport.update({
  id: '/demo3d',
  path: '/demo3d',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetsIndexRoute =
  AuthenticatedProjetsIndexRouteImport.update({
    id: '/projets/',
    path: '/projets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjetsIdRoute = AuthenticatedProjetsIdRouteImport.update({
  id: '/projets/$id',
  path: '/projets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo3d': typeof Demo3dRoute
  '/tarifs': typeof TarifsRoute
  '/api/chat': typeof ApiChatRoute
  '/projets/$id': typeof AuthenticatedProjetsIdRoute
  '/projets/': typeof AuthenticatedProjetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo3d': typeof Demo3dRoute
  '/tarifs': typeof TarifsRoute
  '/api/chat': typeof ApiChatRoute
  '/projets/$id': typeof AuthenticatedProjetsIdRoute
  '/projets': typeof AuthenticatedProjetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo3d': typeof Demo3dRoute
  '/tarifs': typeof TarifsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/projets/$id': typeof AuthenticatedProjetsIdRoute
  '/_authenticated/projets/': typeof AuthenticatedProjetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo3d'
    | '/tarifs'
    | '/api/chat'
    | '/projets/$id'
    | '/projets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo3d'
    | '/tarifs'
    | '/api/chat'
    | '/projets/$id'
    | '/projets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo3d'
    | '/tarifs'
    | '/api/chat'
    | '/_authenticated/projets/$id'
    | '/_authenticated/projets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  Demo3dRoute: typeof Demo3dRoute
  TarifsRoute: typeof TarifsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo3d': {
      id: '/demo3d'
      path: '/demo3d'
      fullPath: '/demo3d'
      preLoaderRoute: typeof Demo3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projets/': {
      id: '/_authenticated/projets/'
      path: '/projets'
      fullPath: '/projets/'
      preLoaderRoute: typeof AuthenticatedProjetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projets/$id': {
      id: '/_authenticated/projets/$id'
      path: '/projets/$id'
      fullPath: '/projets/$id'
      preLoaderRoute: typeof AuthenticatedProjetsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProjetsIdRoute: typeof AuthenticatedProjetsIdRoute
  AuthenticatedProjetsIndexRoute: typeof AuthenticatedProjetsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjetsIdRoute: AuthenticatedProjetsIdRoute,
  AuthenticatedProjetsIndexRoute: AuthenticatedProjetsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  Demo3dRoute: Demo3dRoute,
  TarifsRoute: TarifsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
